jobs:
  update:
    name: Updater
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: python sattxtup.py
on:
  schedule:
  - cron: "30 3 * * *"
